import math
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class EvidenceItem(BaseModel):
    type: str
    name: str
    value: Any
    unit: Optional[str] = None
    timestamp: Optional[str] = None
    confidence: float = 1.0


class ModelConfidence(BaseModel):
    overall: float
    level: str
    calibration_method: str = "NOT_CALIBRATED"


class IrrigationAssessmentResult(BaseModel):
    irrigation_needed: bool
    recommendation_text: str
    urgency: str
    target_water_mm: float
    confidence: ModelConfidence
    evidence_factors: List[EvidenceItem]
    provenance: str = "RULE_BASED"
    explanation: str = ""
    inputs_used: List[str] = Field(default_factory=list)
    inputs_missing: List[str] = Field(default_factory=list)
    crop_threshold_band: Optional[str] = None
    model_version: str = "2.1.0"
    threshold_source: str = "Published ICAR/FAO guidance; not empirically validated against this farm's field outcomes"
    validation_status: str = "UNVALIDATED_AGAINST_FIELD_OUTCOMES"
    domain_disclaimer: str = (
        "This recommendation is generated by a deterministic rule engine based on published "
        "ICAR/FAO moisture threshold guidance. It has not been validated against real farm "
        "field outcomes or agronomist-reviewed performance data."
    )


class IrrigationModelProvider:
    """Deterministic irrigation advisory using explicitly supplied field/weather inputs."""

    def assess_irrigation_needs(
        self,
        soil_moisture: Optional[float],
        air_temp: Optional[float] = None,
        humidity: Optional[float] = None,
        rain_forecast_mm: Optional[float] = None,
        crop: str = "Rice",
        growth_stage: str = "Vegetative",
        last_updated_seconds_ago: int = 0,
        is_simulated: bool = False,
    ) -> IrrigationAssessmentResult:
        inputs_used: List[str] = []
        inputs_missing: List[str] = []
        evidence: List[EvidenceItem] = []

        if soil_moisture is None:
            return IrrigationAssessmentResult(
                irrigation_needed=False,
                recommendation_text="Decision unavailable — required soil moisture input is missing.",
                urgency="NONE",
                target_water_mm=0.0,
                confidence=ModelConfidence(overall=0.0, level="uncertain"),
                evidence_factors=[],
                provenance="UNAVAILABLE",
                explanation="Fresh soil moisture data is required for an irrigation decision.",
                inputs_missing=["soil_moisture"],
            )

        if last_updated_seconds_ago > 21600:
            return IrrigationAssessmentResult(
                irrigation_needed=False,
                recommendation_text="Decision unavailable — sensor data is stale.",
                urgency="NONE",
                target_water_mm=0.0,
                confidence=ModelConfidence(overall=0.0, level="uncertain"),
                evidence_factors=[
                    EvidenceItem(
                        type="sensor",
                        name="last_seen",
                        value=f"{last_updated_seconds_ago // 3600} hours ago",
                        unit="hours",
                    )
                ],
                provenance="UNAVAILABLE",
                explanation="Fresh telemetry is required for a verified irrigation decision.",
                inputs_used=["soil_moisture"],
                inputs_missing=["fresh_soil_moisture"],
            )

        inputs_used.extend(["soil_moisture", "crop", "growth_stage"])
        evidence.append(EvidenceItem(type="sensor", name="soil_moisture", value=soil_moisture, unit="%"))

        if air_temp is not None:
            inputs_used.append("air_temp")
            evidence.append(EvidenceItem(type="weather", name="air_temp", value=air_temp, unit="°C"))
        else:
            inputs_missing.append("air_temp")

        if humidity is not None:
            inputs_used.append("humidity")
            evidence.append(EvidenceItem(type="weather", name="humidity", value=humidity, unit="%"))
        else:
            inputs_missing.append("humidity")

        if rain_forecast_mm is not None:
            inputs_used.append("rain_forecast")
            evidence.append(EvidenceItem(type="weather", name="rain_forecast", value=rain_forecast_mm, unit="mm"))
        else:
            inputs_missing.append("rain_forecast")

        c_lower = crop.lower()
        st_lower = growth_stage.lower()
        if c_lower in ["rice", "paddy"]:
            if "harvest" in st_lower or "ripen" in st_lower:
                min_thresh, max_thresh = 20.0, 35.0
                band_desc = "20.0%–35.0% (Pre-harvest field drying)"
                band_source = "ICAR-IIRR/FAO published rice water-management guidance"
            else:
                min_thresh, max_thresh = 40.0, 60.0
                band_desc = "40.0%–60.0% (Vegetative shallow water / AWD)"
                band_source = "ICAR-IIRR/FAO published rice water-management guidance"
        elif c_lower == "wheat":
            min_thresh, max_thresh = 35.0, 50.0
            band_desc = "35.0%–50.0% (Crown root & tillering)"
            band_source = "ICAR wheat agronomy guidance"
        else:
            min_thresh, max_thresh = 30.0, 50.0
            band_desc = "30.0%–50.0% (Generalized root-zone band)"
            band_source = "FAO generalized crop-water guidance"

        # ET0 is estimated only when temperature is actually supplied.
        et0_estimate = 0.0
        if air_temp is not None:
            et0_estimate = 0.0023 * (air_temp + 17.8) * math.sqrt(max(air_temp - 10, 1)) * 4.5

        if rain_forecast_mm is not None and rain_forecast_mm >= 15.0:
            rec = f"Delay irrigation: {rain_forecast_mm} mm of rainfall is forecast."
            explanation = f"The supplied forecast indicates {rain_forecast_mm} mm of rain."
            urgency = "DELAY_RAIN"
            needed = False
            water_mm = 0.0
        elif soil_moisture < min_thresh:
            needed = True
            urgency = "HIGH" if soil_moisture < (min_thresh - 10) else "MODERATE"
            water_deficit = (min_thresh - soil_moisture) * 0.8
            water_mm = round(water_deficit + et0_estimate, 1)
            rec = f"Apply approximately {water_mm} mm of irrigation to the root zone."
            explanation = f"Soil moisture ({soil_moisture}%) is below the {min_thresh}% threshold for {crop} ({growth_stage})."
        elif soil_moisture > max_thresh:
            needed = False
            urgency = "NONE"
            water_mm = 0.0
            rec = "Discontinue irrigation and ensure field drainage."
            explanation = f"Soil moisture ({soil_moisture}%) exceeds the upper threshold ({max_thresh}%)."
        else:
            needed = False
            urgency = "NONE"
            water_mm = 0.0
            rec = "Maintain the current irrigation schedule."
            explanation = f"Soil moisture ({soil_moisture}%) is within the target band ({band_desc}) for {crop} ({growth_stage})."

        # This is a deterministic rule engine, not a calibrated probabilistic model.
        confidence = ModelConfidence(overall=0.0, level="uncertain")
        provenance = "RULE_BASED (using explicitly supplied simulated telemetry)" if is_simulated else "RULE_BASED"

        return IrrigationAssessmentResult(
            irrigation_needed=needed,
            recommendation_text=rec,
            urgency=urgency,
            target_water_mm=water_mm,
            confidence=confidence,
            evidence_factors=evidence,
            provenance=provenance,
            explanation=explanation,
            inputs_used=inputs_used,
            inputs_missing=inputs_missing,
            crop_threshold_band=band_desc,
            threshold_source=band_source,
            validation_status="UNVALIDATED_AGAINST_FIELD_OUTCOMES",
        )


class NutrientDeficiencyModelProvider:
    """Reports supplied NPK/visual inputs without inventing missing observations."""

    def evaluate(
        self,
        visual_symptoms: Optional[str],
        npk_measured: Optional[Dict[str, float]],
    ) -> Dict[str, Any]:
        has_sensor_npk = bool(npk_measured) and all(k in npk_measured for k in ("N", "P", "K"))

        result: Dict[str, Any] = {
            "status": "UNCONFIRMED",
            "visual_symptoms": visual_symptoms,
            "measured_npk": npk_measured if has_sensor_npk else None,
            "assessment": "No confirmed nutrient deficiency can be determined from the supplied inputs.",
            "confidence": 0.0,
        }

        if visual_symptoms and not has_sensor_npk:
            result["status"] = "UNCONFIRMED_VISUAL_ONLY"
            result["assessment"] = (
                "Visual symptoms were supplied, but visual observation alone does not confirm a nutrient deficiency. "
                "Use a soil or tissue test for confirmation."
            )
        elif has_sensor_npk:
            result["status"] = "MEASURED_NPK_AVAILABLE"
            result["assessment"] = (
                "Measured NPK values are available for interpretation; deficiency thresholds require "
                "validated crop-specific guidance."
            )

        return result


# Kept only as an explicit unavailable compatibility symbol for legacy imports.
vision_provider = None
irrigation_provider = IrrigationModelProvider()
nutrient_provider = NutrientDeficiencyModelProvider()
